---
title: "DataWrangling"
author: "Nicole"
date: "2023-10-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages("plyr")
install.packages("lubridate")
library(lubridate)
library("plyr")
library("dplyr")
library(tidyverse)
library(tidyr)
library(zoo)

```

#Combining Datasets
```{r renaming data}
Total.WQ.Data <- rbind(CCM0069_1993_2003,CCM0069_2003_2013,CCM0069_2013_2023,EE3.0_1984_1993,EE3.0_1993_2003,EE3.0_2003_2013,EE3.0_2013_2023,EE3.1_1984_1993,EE3.1_1993_2003,EE3.1_2003_2013,EE3.1_2013_2023,ET6.1_1984_1993,ET6.1_1993_2003,ET6.1_2003_2013,ET6.1_2013_2023,ET6.2_1984_1993,ET6.2_1993_2003,ET6.2_2003_2013,ET6.2_2013_2023,ET7.1_1984_1993,ET7.1_1993_2003,ET7.1_2003_2013,ET7.1_2013_2023,WQ_1984_1990,WQ_1991_2001,WQ_2002_2012,WQ_2013_2023,TRQ0088_1993_2003,TRQ0088_2003_2013,TRQ0088_2013_2023,TRQ0146_1993_2003,TRQ0146_2003_2013,TRQ0146_2013_2023,WIW0141_1993_2003,WIW0141_2003_2013,WIW0141_2013_2023,XDJ9007_1993_2003,XDJ9007_2003_2013,XDJ9007_2013_2023)
```

#Making a dataset for TN, TP, TSS
```{r}
TN.TP.TSS.Data <- filter(Total.WQ.Data, Parameter == "TN" | Parameter == "TP" | Parameter == "TSS") 
TN.TP.TSS.Data$SampleDate<- as.Date(TN.TP.TSS.Data$SampleDate, format="%m/%d/%Y")
TN.TP.TSS.Data.Processed <- TN.TP.TSS.Data %>%
  select(MonitoringStation, SampleDate, SampleTime, Parameter, MeasureValue, Unit, Latitude, Longitude)

##remove unit column (they're all MG/L)
TN.TP.TSS.Data.Processed <- TN.TP.TSS.Data.Processed %>%
  select(MonitoringStation, SampleDate, SampleTime, Parameter, MeasureValue, Latitude, Longitude)

##pivot wider
TN.TP.TSS.Data.Final <- TN.TP.TSS.Data.Processed %>%
  pivot_wider(names_from = Parameter, 
    values_from = MeasureValue,
    values_fn = mean) 

View(TN.TP.TSS.Data.Final)
class(TN.TP.TSS.Data.Final)

# write.csv(TN.TP.TSS.Data.Processed, row.names = FALSE, file = "~/Master's Project/Data/Processed/TN_TP_TSS_Data_Processed.csv")

write.csv(TN.TP.TSS.Data.Final, row.names = FALSE, file = "../Data/Processed/TN_TP_TSS_Data_Final.csv")
```

```{r}
TN.TP.TSS.Data.Final <- read.csv("../Data/Processed/TN_TP_TSS_Data_Final.csv")

##making year, month, and day columns
TN.TP.TSS.Data.Final <- TN.TP.TSS.Data.Final %>% 
  separate(SampleDate, c("year", "month", "day"))

##fixing short year format
TN.TP.TSS.Data.Final$year[TN.TP.TSS.Data.Final$year=="13"] <- "2013"
TN.TP.TSS.Data.Final$year[TN.TP.TSS.Data.Final$year=="14"] <- "2014"
TN.TP.TSS.Data.Final$year[TN.TP.TSS.Data.Final$year=="15"] <- "2015"
TN.TP.TSS.Data.Final$year[TN.TP.TSS.Data.Final$year=="16"] <- "2016"
TN.TP.TSS.Data.Final$year[TN.TP.TSS.Data.Final$year=="17"] <- "2017"
TN.TP.TSS.Data.Final$year[TN.TP.TSS.Data.Final$year=="18"] <- "2018"
TN.TP.TSS.Data.Final$year[TN.TP.TSS.Data.Final$year=="19"] <- "2019"
TN.TP.TSS.Data.Final$year[TN.TP.TSS.Data.Final$year=="20"] <- "2020"
TN.TP.TSS.Data.Final$year[TN.TP.TSS.Data.Final$year=="21"] <- "2021"
TN.TP.TSS.Data.Final$year[TN.TP.TSS.Data.Final$year=="22"] <- "2022"

##recombining date column
TN.TP.TSS.Data.Final$SampleDate <- paste(TN.TP.TSS.Data.Final$year, TN.TP.TSS.Data.Final$month, TN.TP.TSS.Data.Final$day, sep='-')

TN.TP.TSS.Data.Final <- TN.TP.TSS.Data.Final %>%
  relocate(SampleDate, .after=day)

##converting to date
TN.TP.TSS.Data.Final$SampleDate <- as.Date(TN.TP.TSS.Data.Final$SampleDate, format="%Y-%m-%d")

##creating month_year column
TN.TP.TSS.Data.Final <- TN.TP.TSS.Data.Final %>%
  mutate(year_month = as.yearmon(SampleDate))

TN.TP.TSS.Data.Final <- TN.TP.TSS.Data.Final %>%
  relocate(year_month, .after=SampleDate)

##grouping by site and year_month
TN.TP.TSS.Data.Final <- TN.TP.TSS.Data.Final %>%
  group_by(MonitoringStation, Latitude, Longitude, year_month) %>%
  summarize(meanTN = mean(TN),
            meanTP = mean(TP),
            meanTSS = mean(TSS))

##change yearmon object to date object
TN.TP.TSS.Data.Final$year_month <- as.Date(TN.TP.TSS.Data.Final$year_month, format = "%Y-%m-%d")
class(TN.TP.TSS.Data.Final$year_month)

```

## Separate by station for time series
```{r}
BXK0031_TN_TP_TSS <- filter(TN.TP.TSS.Data.Final, MonitoringStation == "BXK0031")
CCM0069_TN_TP_TSS <- filter(TN.TP.TSS.Data.Final, MonitoringStation == "CCM0069")
EE3.0_TN_TP_TSS <- filter(TN.TP.TSS.Data.Final, MonitoringStation == "EE3.0")
EE3.1_TN_TP_TSS <- filter(TN.TP.TSS.Data.Final, MonitoringStation == "EE3.1")
EE3.2_TN_TP_TSS <- filter(TN.TP.TSS.Data.Final, MonitoringStation == "EE3.2")
EE3.3_TN_TP_TSS <- filter(TN.TP.TSS.Data.Final, MonitoringStation == "EE3.3")
ET6.1_TN_TP_TSS <- filter(TN.TP.TSS.Data.Final, MonitoringStation == "ET6.1")
ET6.2_TN_TP_TSS <- filter(TN.TP.TSS.Data.Final, MonitoringStation == "ET6.2")
ET7.1_TN_TP_TSS <- filter(TN.TP.TSS.Data.Final, MonitoringStation == "ET7.1")
ET8.1_TN_TP_TSS <- filter(TN.TP.TSS.Data.Final, MonitoringStation == "ET8.1")
ET9.1_TN_TP_TSS <- filter(TN.TP.TSS.Data.Final, MonitoringStation == "ET9.1")
ET10.1_TN_TP_TSS <- filter(TN.TP.TSS.Data.Final, MonitoringStation == "ET10.1")
MNK0146_TN_TP_TSS <- filter(TN.TP.TSS.Data.Final, MonitoringStation == "MNK0146")
POK0087_TN_TP_TSS <- filter(TN.TP.TSS.Data.Final, MonitoringStation == "POK0087")
TRQ0088_TN_TP_TSS <- filter(TN.TP.TSS.Data.Final, MonitoringStation == "TRQ0088")
TRQ0146_TN_TP_TSS <- filter(TN.TP.TSS.Data.Final, MonitoringStation == "TRQ0146")
WIW0141_TN_TP_TSS <- filter(TN.TP.TSS.Data.Final, MonitoringStation == "WIW0141")
WIW0144_TN_TP_TSS <- filter(TN.TP.TSS.Data.Final, MonitoringStation == "WIW0144")
XAK7810_TN_TP_TSS <- filter(TN.TP.TSS.Data.Final, MonitoringStation == "XAK7810")
XCI4078_TN_TP_TSS <- filter(TN.TP.TSS.Data.Final, MonitoringStation == "XCI4078")
XDJ9007_TN_TP_TSS <- filter(TN.TP.TSS.Data.Final, MonitoringStation == "XDJ9007")
```

## Exploratory Analysis 
## (note: changed SampleDate to year_month and TN to meanTN)
```{r}
list.dfs <- list(BXK0031_TN_TP_TSS,CCM0069_TN_TP_TSS,EE3.0_TN_TP_TSS,EE3.1_TN_TP_TSS,EE3.2_TN_TP_TSS,EE3.3_TN_TP_TSS,ET6.1_TN_TP_TSS,ET6.2_TN_TP_TSS,ET7.1_TN_TP_TSS,ET8.1_TN_TP_TSS,ET9.1_TN_TP_TSS,ET10.1_TN_TP_TSS,MNK0146_TN_TP_TSS,POK0087_TN_TP_TSS,TRQ0088_TN_TP_TSS,TRQ0146_TN_TP_TSS,WIW0141_TN_TP_TSS,XAK7810_TN_TP_TSS,XCI4078_TN_TP_TSS,XDJ9007_TN_TP_TSS)

# Representing trends in TN over time at each site
plot.TN.chrs <- function(list.dfs) { 
  plot.list <- vector(mode = 'list', length = length(list.dfs))
  
  for (i in 1:length(list.dfs)) {
    plot.list[[i]] <- ggplot(list.dfs[[i]], aes(x=year_month, y=meanTN)) +
                      geom_line() +
                      ggtitle(list.dfs[[i]]$MonitoringStation)
    names(plot.list)[i] <- paste0(list.dfs[[i]]$MonitoringStation)
  }
  return(plot.list)
}
plot.TN.chrs(list.dfs)

```
## Exploratory Analysis for TP
```{r}
plot.TP.chrs <- function(list.dfs) { 
  plot.list <- vector(mode = 'list', length = length(list.dfs))
  
  for (i in 1:length(list.dfs)) {
    plot.list[[i]] <- ggplot(list.dfs[[i]], aes(x=year_month, y=meanTP)) +
                      geom_line() +
                      ggtitle(list.dfs[[i]]$MonitoringStation)
    names(plot.list)[i] <- paste0(list.dfs[[i]]$MonitoringStation)
  }
  return(plot.list)
}
plot.TP.chrs(list.dfs)
```

## Exploratory Analysis for TSS
```{r}
plot.TSS.chrs <- function(list.dfs) { 
  plot.list <- vector(mode = 'list', length = length(list.dfs))
  
  for (i in 1:length(list.dfs)) {
    plot.list[[i]] <- ggplot(list.dfs[[i]], aes(x=year_month, y=meanTSS)) +
                      geom_line() +
                      ggtitle(list.dfs[[i]]$MonitoringStation)
    names(plot.list)[i] <- paste0(list.dfs[[i]]$MonitoringStation)
  }
  return(plot.list)
}
plot.TSS.chrs(list.dfs)
```

## Removing data gaps
```{r}
##change formatting
BXK0031_TN_TP_TSS.Complete <- BXK0031_TN_TP_TSS %>%
  filter(year_month <= as.Date("2013-12-01"))
##ordering dataframe
  BXK0031_TN_TP_TSS.Complete <- BXK0031_TN_TP_TSS.Complete[order(BXK0031_TN_TP_TSS.Complete$year_month),]
##remove NA rows
BXK0031_TN_TP_TSS.Complete <- BXK0031_TN_TP_TSS.Complete[!is.na(BXK0031_TN_TP_TSS.Complete$MonitoringStation),]

##CCM0069
CCM0069_TN_TP_TSS.Complete <- CCM0069_TN_TP_TSS %>%
  filter(year_month <= as.Date("2013-12-01"))
CCM0069_TN_TP_TSS.Complete <- CCM0069_TN_TP_TSS.Complete[order(CCM0069_TN_TP_TSS.Complete$year_month),]
CCM0069_TN_TP_TSS.Complete <- CCM0069_TN_TP_TSS.Complete[!is.na(CCM0069_TN_TP_TSS.Complete$MonitoringStation),]
  nrow(CCM0069_TN_TP_TSS.Complete)
  #Interpolate for NAs
CCM0069_TN_TP_TSS.Complete <- CCM0069_TN_TP_TSS.Complete %>%
  mutate(meanTN = zoo::na.approx(meanTN))
CCM0069_TN_TP_TSS.Complete <- CCM0069_TN_TP_TSS.Complete %>%
  mutate(meanTP = zoo::na.approx(meanTP))
CCM0069_TN_TP_TSS.Complete <- CCM0069_TN_TP_TSS.Complete %>%
  mutate(meanTSS = zoo::na.approx(meanTSS))

##3.0   
EE3.0_TN_TP_TSS.Complete <- EE3.0_TN_TP_TSS %>%
  filter(year_month <= as.Date("2022-12-01"))
EE3.0_TN_TP_TSS.Complete <- EE3.0_TN_TP_TSS.Complete[order(EE3.0_TN_TP_TSS.Complete$year_month),]
EE3.0_TN_TP_TSS.Complete <- EE3.0_TN_TP_TSS.Complete[!is.na(EE3.0_TN_TP_TSS.Complete$MonitoringStation),]
##Creating sequence of dates
EE3.0_yearmon <- as.data.frame(seq(from=as.Date("1986-01-01"), 
                                   to=as.Date("2022-12-01"),
                                   by="1 month"))
colnames(EE3.0_yearmon)[1] <- "year_month"
nrow(EE3.0_yearmon)
##Merging dataframes 
EE3.0_TN_TP_TSS.Merged <- merge(EE3.0_TN_TP_TSS.Complete, EE3.0_yearmon, by="year_month", all=T)
nrow(EE3.0_TN_TP_TSS.Merged)
##Filling NAs for station, latitude, longitude
EE3.0_TN_TP_TSS.Merged <- EE3.0_TN_TP_TSS.Merged %>%
  relocate(year_month, .after=Longitude) %>%
  replace_na(list(MonitoringStation="EE3.0", Latitude=38.28093, Longitude=-76.01033))
 #Interpolate for NAs
EE3.0_TN_TP_TSS.Merged <- EE3.0_TN_TP_TSS.Merged %>%
  mutate(meanTN = zoo::na.approx(meanTN))
EE3.0_TN_TP_TSS.Merged <- EE3.0_TN_TP_TSS.Merged %>%
  mutate(meanTP = zoo::na.approx(meanTP))

##EE3.1
EE3.1_TN_TP_TSS.Complete <- EE3.1_TN_TP_TSS %>%
  filter(year_month <= as.Date("2022-12-01"))
EE3.1_TN_TP_TSS.Complete <- EE3.1_TN_TP_TSS.Complete[order(EE3.1_TN_TP_TSS.Complete$year_month),]
EE3.1_TN_TP_TSS.Complete <- EE3.1_TN_TP_TSS.Complete[!is.na(EE3.1_TN_TP_TSS.Complete$MonitoringStation),]
##Creating sequence of dates
EE3.1_yearmon <- as.data.frame(seq(from=as.Date("1984-10-01"), 
                                   to=as.Date("2022-12-01"),
                                   by="1 month"))
colnames(EE3.1_yearmon)[1] <- "year_month"
nrow(EE3.1_yearmon)
##Merging dataframes 
EE3.1_TN_TP_TSS.Merged <- merge(EE3.1_TN_TP_TSS.Complete, EE3.1_yearmon, by="year_month", all=T)
nrow(EE3.1_TN_TP_TSS.Merged)
##Filling NAs for station, latitude, longitude
EE3.1_TN_TP_TSS.Merged <- EE3.1_TN_TP_TSS.Merged %>%
  relocate(year_month, .after=Longitude) %>%
  replace_na(list(MonitoringStation="EE3.1", Latitude=38.19685, Longitude=-75.97321))
#Interpolate for NAs
EE3.1_TN_TP_TSS.Merged <- EE3.1_TN_TP_TSS.Merged %>%
  mutate(meanTN = zoo::na.approx(meanTN))
EE3.1_TN_TP_TSS.Merged <- EE3.1_TN_TP_TSS.Merged %>%
  mutate(meanTP = zoo::na.approx(meanTP))
EE3.1_TN_TP_TSS.Merged <- EE3.1_TN_TP_TSS.Merged %>%
  mutate(meanTSS = zoo::na.approx(meanTSS))

##EE3.2
EE3.2_TN_TP_TSS.Complete <- EE3.2_TN_TP_TSS %>%
  filter(year_month <= as.Date("2022-12-01"))
EE3.2_TN_TP_TSS.Complete <- EE3.2_TN_TP_TSS.Complete[order(EE3.2_TN_TP_TSS.Complete$year_month),]
EE3.2_TN_TP_TSS.Complete <- EE3.2_TN_TP_TSS.Complete[!is.na(EE3.2_TN_TP_TSS.Complete$MonitoringStation),]
##Creating sequence of dates
EE3.2_yearmon <- as.data.frame(seq(from=as.Date("1986-03-01"), 
                                   to=as.Date("2022-12-01"),
                                   by="1 month"))
colnames(EE3.2_yearmon)[1] <- "year_month"
nrow(EE3.2_yearmon)
##Merging dataframes 
EE3.2_TN_TP_TSS.Merged <- merge(EE3.2_TN_TP_TSS.Complete, EE3.2_yearmon, by="year_month", all=T)
nrow(EE3.2_TN_TP_TSS.Merged)
##Filling NAs for station, latitude, longitude
EE3.2_TN_TP_TSS.Merged <- EE3.2_TN_TP_TSS.Merged %>%
  relocate(year_month, .after=Longitude) %>%
  replace_na(list(MonitoringStation="EE3.2", Latitude=37.98139, Longitude=-75.92423))
#Interpolate for NAs
EE3.2_TN_TP_TSS.Merged <- EE3.2_TN_TP_TSS.Merged %>%
  mutate(meanTN = zoo::na.approx(meanTN))
EE3.2_TN_TP_TSS.Merged <- EE3.2_TN_TP_TSS.Merged %>%
  mutate(meanTP = zoo::na.approx(meanTP))
EE3.2_TN_TP_TSS.Merged <- EE3.2_TN_TP_TSS.Merged %>%
  mutate(meanTSS = zoo::na.approx(meanTSS))

##EE3.3
EE3.3_TN_TP_TSS.Complete <- EE3.3_TN_TP_TSS %>%
  filter(year_month <= as.Date("2022-12-01"))
EE3.3_TN_TP_TSS.Complete <- EE3.3_TN_TP_TSS.Complete[order(EE3.3_TN_TP_TSS.Complete$year_month),]
EE3.3_TN_TP_TSS.Complete <- EE3.3_TN_TP_TSS.Complete[!is.na(EE3.3_TN_TP_TSS.Complete$MonitoringStation),]
##Creating sequence of dates
EE3.3_yearmon <- as.data.frame(seq(from=as.Date("1986-03-01"), 
                                   to=as.Date("2022-12-01"),
                                   by="1 month"))
colnames(EE3.3_yearmon)[1] <- "year_month"
nrow(EE3.3_yearmon)
##Merging dataframes 
EE3.3_TN_TP_TSS.Merged <- merge(EE3.3_TN_TP_TSS.Complete, EE3.3_yearmon, by="year_month", all=T)
nrow(EE3.3_TN_TP_TSS.Merged)
##Filling NAs for station, latitude, longitude
EE3.3_TN_TP_TSS.Merged <- EE3.3_TN_TP_TSS.Merged %>%
  relocate(year_month, .after=Longitude) %>%
  replace_na(list(MonitoringStation="EE3.3", Latitude=37.91455, Longitude=-75.80148))
#Interpolate for NAs
EE3.3_TN_TP_TSS.Merged <- EE3.3_TN_TP_TSS.Merged %>%
  mutate(meanTN = zoo::na.approx(meanTN))
EE3.3_TN_TP_TSS.Merged <- EE3.3_TN_TP_TSS.Merged %>%
  mutate(meanTP = zoo::na.approx(meanTP))
EE3.3_TN_TP_TSS.Merged <- EE3.3_TN_TP_TSS.Merged %>%
  mutate(meanTSS = zoo::na.approx(meanTSS))

## ET6.1
ET6.1_TN_TP_TSS.Complete <- ET6.1_TN_TP_TSS %>%
  filter(year_month <= as.Date("2022-12-01"))
ET6.1_TN_TP_TSS.Complete <- ET6.1_TN_TP_TSS.Complete[order(ET6.1_TN_TP_TSS.Complete$year_month),]
ET6.1_TN_TP_TSS.Complete <- ET6.1_TN_TP_TSS.Complete[!is.na(ET6.1_TN_TP_TSS.Complete$MonitoringStation),]
##Creating sequence of dates
ET6.1_yearmon <- as.data.frame(seq(from=as.Date("1986-01-01"), 
                                   to=as.Date("2022-12-01"),
                                   by="1 month"))
colnames(ET6.1_yearmon)[1] <- "year_month"
nrow(ET6.1_yearmon)
##Merging dataframes 
ET6.1_TN_TP_TSS.Merged <- merge(ET6.1_TN_TP_TSS.Complete, ET6.1_yearmon, by="year_month", all=T)
nrow(ET6.1_TN_TP_TSS.Merged)
##Filling NAs for station, latitude, longitude
ET6.1_TN_TP_TSS.Merged <- ET6.1_TN_TP_TSS.Merged %>%
  relocate(year_month, .after=Longitude) %>%
  replace_na(list(MonitoringStation="ET6.1", Latitude=38.54833, Longitude=-75.70306))
#Interpolate for NAs
ET6.1_TN_TP_TSS.Merged <- ET6.1_TN_TP_TSS.Merged %>%
  mutate(meanTN = zoo::na.approx(meanTN))
ET6.1_TN_TP_TSS.Merged <- ET6.1_TN_TP_TSS.Merged %>%
  mutate(meanTP = zoo::na.approx(meanTP))
ET6.1_TN_TP_TSS.Merged <- ET6.1_TN_TP_TSS.Merged %>%
  mutate(meanTSS = zoo::na.approx(meanTSS))

## ET6.2
ET6.2_TN_TP_TSS.Complete <- ET6.2_TN_TP_TSS %>%
  filter(year_month <= as.Date("2022-12-01"))
ET6.2_TN_TP_TSS.Complete <- ET6.2_TN_TP_TSS.Complete[order(ET6.2_TN_TP_TSS.Complete$year_month),]
ET6.2_TN_TP_TSS.Complete <- ET6.2_TN_TP_TSS.Complete[!is.na(ET6.2_TN_TP_TSS.Complete$MonitoringStation),]
##Creating sequence of dates
ET6.2_yearmon <- as.data.frame(seq(from=as.Date("1986-01-01"), 
                                   to=as.Date("2022-12-01"),
                                   by="1 month"))
colnames(ET6.2_yearmon)[1] <- "year_month"
nrow(ET6.2_yearmon)
##Merging dataframes 
ET6.2_TN_TP_TSS.Merged <- merge(ET6.2_TN_TP_TSS.Complete, ET6.2_yearmon, by="year_month", all=T)
nrow(ET6.2_TN_TP_TSS.Merged)
##Filling NAs for station, latitude, longitude
ET6.2_TN_TP_TSS.Merged <- ET6.2_TN_TP_TSS.Merged %>%
  relocate(year_month, .after=Longitude) %>%
  replace_na(list(MonitoringStation="ET6.2", Latitude=38.34133, Longitude=-75.88834))
#Interpolate for NAs
ET6.2_TN_TP_TSS.Merged <- ET6.2_TN_TP_TSS.Merged %>%
  mutate(meanTN = zoo::na.approx(meanTN))
ET6.2_TN_TP_TSS.Merged <- ET6.2_TN_TP_TSS.Merged %>%
  mutate(meanTP = zoo::na.approx(meanTP))
ET6.2_TN_TP_TSS.Merged <- ET6.2_TN_TP_TSS.Merged %>%
  mutate(meanTSS = zoo::na.approx(meanTSS))

#ET7.1
ET7.1_TN_TP_TSS.Complete <- ET7.1_TN_TP_TSS %>%
  filter(year_month <= as.Date("2022-12-01"))
ET7.1_TN_TP_TSS.Complete <- ET7.1_TN_TP_TSS.Complete[order(ET7.1_TN_TP_TSS.Complete$year_month),]
ET7.1_TN_TP_TSS.Complete <- ET7.1_TN_TP_TSS.Complete[!is.na(ET7.1_TN_TP_TSS.Complete$MonitoringStation),]
##Creating sequence of dates
ET7.1_yearmon <- as.data.frame(seq(from=as.Date("1986-01-01"), 
                                   to=as.Date("2022-12-01"),
                                   by="1 month"))
colnames(ET7.1_yearmon)[1] <- "year_month"
nrow(ET7.1_yearmon)
##Merging dataframes 
ET7.1_TN_TP_TSS.Merged <- merge(ET7.1_TN_TP_TSS.Complete, ET7.1_yearmon, by="year_month", all=T)
nrow(ET7.1_TN_TP_TSS.Merged)
##Filling NAs for station, latitude, longitude
ET7.1_TN_TP_TSS.Merged <- ET7.1_TN_TP_TSS.Merged %>%
  relocate(year_month, .after=Longitude) %>%
  replace_na(list(MonitoringStation="ET7.1", Latitude=38.26783, Longitude=-75.78793))
#Interpolate for NAs
ET7.1_TN_TP_TSS.Merged <- ET7.1_TN_TP_TSS.Merged %>%
  mutate(meanTN = zoo::na.approx(meanTN))
ET7.1_TN_TP_TSS.Merged <- ET7.1_TN_TP_TSS.Merged %>%
  mutate(meanTP = zoo::na.approx(meanTP))
ET7.1_TN_TP_TSS.Merged <- ET7.1_TN_TP_TSS.Merged %>%
  mutate(meanTSS = zoo::na.approx(meanTSS))

##ET8.1
ET8.1_TN_TP_TSS.Complete <- ET8.1_TN_TP_TSS %>%
  filter(year_month <= as.Date("2022-12-01"))
ET8.1_TN_TP_TSS.Complete <- ET8.1_TN_TP_TSS.Complete[order(ET8.1_TN_TP_TSS.Complete$year_month),]
ET8.1_TN_TP_TSS.Complete <- ET8.1_TN_TP_TSS.Complete[!is.na(ET8.1_TN_TP_TSS.Complete$MonitoringStation),]
##Creating sequence of dates
ET8.1_yearmon <- as.data.frame(seq(from=as.Date("1986-03-01"), 
                                   to=as.Date("2022-12-01"),
                                   by="1 month"))
colnames(ET8.1_yearmon)[1] <- "year_month"
nrow(ET8.1_yearmon)
##Merging dataframes 
ET8.1_TN_TP_TSS.Merged <- merge(ET8.1_TN_TP_TSS.Complete, ET8.1_yearmon, by="year_month", all=T)
nrow(ET8.1_TN_TP_TSS.Merged)
##Filling NAs for station, latitude, longitude
ET8.1_TN_TP_TSS.Merged <- ET8.1_TN_TP_TSS.Merged %>%
  relocate(year_month, .after=Longitude) %>%
  replace_na(list(MonitoringStation="ET8.1", Latitude=38.13794, Longitude=-75.81411))
#Interpolate for NAs
ET8.1_TN_TP_TSS.Merged <- ET8.1_TN_TP_TSS.Merged %>%
  mutate(meanTN = zoo::na.approx(meanTN))
ET8.1_TN_TP_TSS.Merged <- ET8.1_TN_TP_TSS.Merged %>%
  mutate(meanTP = zoo::na.approx(meanTP))
ET8.1_TN_TP_TSS.Merged <- ET8.1_TN_TP_TSS.Merged %>%
  mutate(meanTSS = zoo::na.approx(meanTSS))

# ET9.1
ET9.1_TN_TP_TSS.Complete <- ET9.1_TN_TP_TSS %>%
  filter(year_month <= as.Date("2022-12-01"))
ET9.1_TN_TP_TSS.Complete <- ET9.1_TN_TP_TSS.Complete[order(ET9.1_TN_TP_TSS.Complete$year_month),]
ET9.1_TN_TP_TSS.Complete <- ET9.1_TN_TP_TSS.Complete[!is.na(ET9.1_TN_TP_TSS.Complete$MonitoringStation),]
##Creating sequence of dates
ET9.1_yearmon <- as.data.frame(seq(from=as.Date("1986-03-01"), 
                                   to=as.Date("2022-12-01"),
                                   by="1 month"))
colnames(ET9.1_yearmon)[1] <- "year_month"
nrow(ET9.1_yearmon)
##Merging dataframes 
ET9.1_TN_TP_TSS.Merged <- merge(ET9.1_TN_TP_TSS.Complete, ET9.1_yearmon, by="year_month", all=T)
nrow(ET9.1_TN_TP_TSS.Merged)
##Filling NAs for station, latitude, longitude
ET9.1_TN_TP_TSS.Merged <- ET9.1_TN_TP_TSS.Merged %>%
  relocate(year_month, .after=Longitude) %>%
  replace_na(list(MonitoringStation="ET9.1", Latitude=38.055, Longitude=-75.80167))
##Interpolate for NAs
ET9.1_TN_TP_TSS.Merged <- ET9.1_TN_TP_TSS.Merged %>%
  mutate(meanTN = zoo::na.approx(meanTN))
ET9.1_TN_TP_TSS.Merged <- ET9.1_TN_TP_TSS.Merged %>%
  mutate(meanTP = zoo::na.approx(meanTP))
ET9.1_TN_TP_TSS.Merged <- ET9.1_TN_TP_TSS.Merged %>%
  mutate(meanTSS = zoo::na.approx(meanTSS))

#ET10.1
ET10.1_TN_TP_TSS.Complete <- ET10.1_TN_TP_TSS %>%
  filter(year_month <= as.Date("2022-12-01"))
ET10.1_TN_TP_TSS.Complete <- ET10.1_TN_TP_TSS.Complete[order(ET10.1_TN_TP_TSS.Complete$year_month),]
ET10.1_TN_TP_TSS.Complete <- ET10.1_TN_TP_TSS.Complete[!is.na(ET10.1_TN_TP_TSS.Complete$MonitoringStation),]
##Creating sequence of dates
ET10.1_yearmon <- as.data.frame(seq(from=as.Date("1986-01-01"), 
                                   to=as.Date("2022-12-01"),
                                   by="1 month"))
colnames(ET10.1_yearmon)[1] <- "year_month"
nrow(ET10.1_yearmon)
##Merging dataframes 
ET10.1_TN_TP_TSS.Merged <- merge(ET10.1_TN_TP_TSS.Complete, ET10.1_yearmon, by="year_month", all=T)
nrow(ET10.1_TN_TP_TSS.Merged)
##Filling NAs for station, latitude, longitude
ET10.1_TN_TP_TSS.Merged <- ET10.1_TN_TP_TSS.Merged %>%
  relocate(year_month, .after=Longitude) %>%
  replace_na(list(MonitoringStation="ET10.1", Latitude=38.07614, Longitude=-75.57125))
##Interpolate for NAs
ET10.1_TN_TP_TSS.Merged <- ET10.1_TN_TP_TSS.Merged %>%
  mutate(meanTN = zoo::na.approx(meanTN))
ET10.1_TN_TP_TSS.Merged <- ET10.1_TN_TP_TSS.Merged %>%
  mutate(meanTP = zoo::na.approx(meanTP))
ET10.1_TN_TP_TSS.Merged <- ET10.1_TN_TP_TSS.Merged %>%
  mutate(meanTSS = zoo::na.approx(meanTSS))

#MNK0146
MNK0146_TN_TP_TSS.Complete <- MNK0146_TN_TP_TSS %>%
  filter(year_month <= as.Date("2013-12-01"))
MNK0146_TN_TP_TSS.Complete <- MNK0146_TN_TP_TSS.Complete[order(MNK0146_TN_TP_TSS.Complete$year_month),]
MNK0146_TN_TP_TSS.Complete <- MNK0146_TN_TP_TSS.Complete[!is.na(MNK0146_TN_TP_TSS.Complete$MonitoringStation),]
##Creating sequence of dates
MNK0146_yearmon <- as.data.frame(seq(from=as.Date("2003-04-01"), 
                                   to=as.Date("2013-12-01"),
                                   by="1 month"))
colnames(MNK0146_yearmon)[1] <- "year_month"
nrow(MNK0146_yearmon)
##Merging dataframes 
MNK0146_TN_TP_TSS.Merged <- merge(MNK0146_TN_TP_TSS.Complete, MNK0146_yearmon, by="year_month", all=T)
nrow(MNK0146_TN_TP_TSS.Merged)
##Filling NAs for station, latitude, longitude
MNK0146_TN_TP_TSS.Merged <- MNK0146_TN_TP_TSS.Merged %>%
  relocate(year_month, .after=Longitude) %>%
  replace_na(list(MonitoringStation="MNK0146", Latitude=38.175, Longitude=-75.72361))
##Interpolate for NAs
MNK0146_TN_TP_TSS.Merged <- MNK0146_TN_TP_TSS.Merged %>%
  mutate(meanTN = zoo::na.approx(meanTN))
MNK0146_TN_TP_TSS.Merged <- MNK0146_TN_TP_TSS.Merged %>%
  mutate(meanTP = zoo::na.approx(meanTP))
MNK0146_TN_TP_TSS.Merged <- MNK0146_TN_TP_TSS.Merged %>%
  mutate(meanTSS = zoo::na.approx(meanTSS))

#POK0087
POK0087_TN_TP_TSS.Complete <- POK0087_TN_TP_TSS %>%
  filter(year_month <= as.Date("2014-10-01"))
POK0087_TN_TP_TSS.Complete <- POK0087_TN_TP_TSS.Complete[order(POK0087_TN_TP_TSS.Complete$year_month),]
POK0087_TN_TP_TSS.Complete <- POK0087_TN_TP_TSS.Complete[!is.na(POK0087_TN_TP_TSS.Complete$MonitoringStation),]
##Creating sequence of dates
### most stop after 2013-3 for TN, TP
POK0087_yearmon <- as.data.frame(seq(from=as.Date("2003-03-01"), 
                                   to=as.Date("2014-10-01"),
                                   by="1 month"))
colnames(POK0087_yearmon)[1] <- "year_month"
nrow(POK0087_yearmon)
##Merging dataframes 
POK0087_TN_TP_TSS.Merged <- merge(POK0087_TN_TP_TSS.Complete, POK0087_yearmon, by="year_month", all=T)
nrow(POK0087_TN_TP_TSS.Merged)
##Filling NAs for station, latitude, longitude
POK0087_TN_TP_TSS.Merged <- POK0087_TN_TP_TSS.Merged %>%
  relocate(year_month, .after=Longitude) %>%
  replace_na(list(MonitoringStation="POK0087", Latitude=38.03972, Longitude=-75.66084))
##Making two datasets because of missing TN and TP data
POKOO87_TN_TP.Merged <- POK0087_TN_TP_TSS.Merged %>%
  select(MonitoringStation, Latitude, Longitude, year_month, meanTN, meanTP)
POK0087_TN_TP.Merged <- POK0087_TN_TP_TSS %>%
  filter(year_month <= as.Date("2012-03-01"))
##Interpolate for NAs
POK0087_TN_TP.Merged <- POK0087_TN_TP.Merged %>%
  mutate(meanTN = zoo::na.approx(meanTN))
POK0087_TN_TP.Merged <- POK0087_TN_TP.Merged %>%
  mutate(meanTP = zoo::na.approx(meanTP))
POK0087_TN_TP_TSS.Merged <- POK0087_TN_TP_TSS.Merged %>%
  mutate(meanTSS = zoo::na.approx(meanTSS))

#TRQ0088
TRQ0088_TN_TP_TSS.Complete <- TRQ0088_TN_TP_TSS %>%
  filter(year_month <= as.Date("2013-12-01"))
TRQ0088_TN_TP_TSS.Complete <- TRQ0088_TN_TP_TSS.Complete[order(TRQ0088_TN_TP_TSS.Complete$year_month),]
TRQ0088_TN_TP_TSS.Complete <- TRQ0088_TN_TP_TSS.Complete[!is.na(TRQ0088_TN_TP_TSS.Complete$MonitoringStation),]
##Interpolate for NAs
TRQ0088_TN_TP_TSS.Complete <- TRQ0088_TN_TP_TSS.Complete %>%
  mutate(meanTN = zoo::na.approx(meanTN))
TRQ0088_TN_TP_TSS.Complete <- TRQ0088_TN_TP_TSS.Complete %>%
  mutate(meanTP = zoo::na.approx(meanTP))
TRQ0088_TN_TP_TSS.Complete <- TRQ0088_TN_TP_TSS.Complete %>%
  mutate(meanTSS = zoo::na.approx(meanTSS))

#TRQ0146
TRQ0146_TN_TP_TSS.Complete <- TRQ0146_TN_TP_TSS %>%
  filter(year_month <= as.Date("2013-12-01"))
TRQ0146_TN_TP_TSS.Complete <- TRQ0146_TN_TP_TSS.Complete[order(TRQ0146_TN_TP_TSS.Complete$year_month),]
TRQ0146_TN_TP_TSS.Complete <- TRQ0146_TN_TP_TSS.Complete[!is.na(TRQ0146_TN_TP_TSS.Complete$MonitoringStation),]
##Interpolate for NAs
TRQ0146_TN_TP_TSS.Complete <- TRQ0146_TN_TP_TSS.Complete %>%
  mutate(meanTN = zoo::na.approx(meanTN))
TRQ0146_TN_TP_TSS.Complete <- TRQ0146_TN_TP_TSS.Complete %>%
  mutate(meanTP = zoo::na.approx(meanTP))

#WIW0141
WIW0141_TN_TP_TSS.Complete <- WIW0141_TN_TP_TSS %>%
  filter(year_month <= as.Date("2022-11-01"))
WIW0141_TN_TP_TSS.Complete <- WIW0141_TN_TP_TSS.Complete[order(WIW0141_TN_TP_TSS.Complete$year_month),]
WIW0141_TN_TP_TSS.Complete <- WIW0141_TN_TP_TSS.Complete[!is.na(WIW0141_TN_TP_TSS.Complete$MonitoringStation),]
##Creating sequence of dates
WIW0141_yearmon <- as.data.frame(seq(from=as.Date("2003-03-01"), 
                                   to=as.Date("2022-11-01"),
                                   by="1 month"))
colnames(WIW0141_yearmon)[1] <- "year_month"
nrow(WIW0141_yearmon)
##Merging dataframes 
WIW0141_TN_TP_TSS.Merged <- merge(WIW0141_TN_TP_TSS.Complete, WIW0141_yearmon, by="year_month", all=T)
nrow(WIW0141_TN_TP_TSS.Merged)
##Filling NAs for station, latitude, longitude
WIW0141_TN_TP_TSS.Merged <- WIW0141_TN_TP_TSS.Merged %>%
  relocate(year_month, .after=Longitude) %>%
  replace_na(list(MonitoringStation="WIW0141", Latitude=38.34153, Longitude=-75.69569))

XAK7810_TN_TP_TSS.Complete <- XAK7810_TN_TP_TSS %>%
 filter(year_month <= as.Date("2014-10-01"))
XAK7810_TN_TP_TSS.Complete <- XAK7810_TN_TP_TSS.Complete[order(XAK7810_TN_TP_TSS.Complete$year_month),]
XAK7810_TN_TP_TSS.Complete <- XAK7810_TN_TP_TSS.Complete[!is.na(XAK7810_TN_TP_TSS.Complete$MonitoringStation),]
##Creating sequence of dates
XAK7810_yearmon <- as.data.frame(seq(from=as.Date("2003-03-01"), 
                                   to=as.Date("2014-10-01"),
                                   by="1 month"))
colnames(XAK7810_yearmon)[1] <- "year_month"
nrow(XAK7810_yearmon)
##Merging dataframes 
XAK7810_TN_TP_TSS.Merged <- merge(XAK7810_TN_TP_TSS.Complete, XAK7810_yearmon, by="year_month", all=T)
nrow(XAK7810_TN_TP_TSS.Merged)
##Filling NAs for station, latitude, longitude
XAK7810_TN_TP_TSS.Merged <- XAK7810_TN_TP_TSS.Merged %>%
  relocate(year_month, .after=Longitude) %>%
  replace_na(list(MonitoringStation="XAK7810", Latitude=37.96395, Longitude=-75.65047))
#Separating TN and TP because they have large data gaps
XAK7810_TN_TP.Merged <- XAK7810_TN_TP_TSS.Merged %>%
  select(MonitoringStation, Latitude, Longitude, year_month, meanTN, meanTP)
XAK7810_TN_TP.Merged <- XAK7810_TN_TP_TSS %>%
  filter(year_month <= as.Date("2012-03-01"))

XCI4078_TN_TP_TSS.Complete <- XCI4078_TN_TP_TSS %>%
  filter(year_month <= as.Date("2013-12-01"))
XCI4078_TN_TP_TSS.Complete <- XCI4078_TN_TP_TSS.Complete[order(XCI4078_TN_TP_TSS.Complete$year_month),]
XCI4078_TN_TP_TSS.Complete <- XCI4078_TN_TP_TSS.Complete[!is.na(XCI4078_TN_TP_TSS.Complete$MonitoringStation),]
##Creating sequence of dates
XCI4078_yearmon <- as.data.frame(seq(from=as.Date("2003-03-01"), 
                                   to=as.Date("2013-12-01"),
                                   by="1 month"))
colnames(XCI4078_yearmon)[1] <- "year_month"
nrow(XCI4078_yearmon)
##Merging dataframes 
XCI4078_TN_TP_TSS.Merged <- merge(XCI4078_TN_TP_TSS.Complete, XCI4078_yearmon, by="year_month", all=T)
nrow(XCI4078_TN_TP_TSS.Merged)
##Filling NAs for station, latitude, longitude
XCI4078_TN_TP_TSS.Merged <- XCI4078_TN_TP_TSS.Merged %>%
  relocate(year_month, .after=Longitude) %>%
  replace_na(list(MonitoringStation="XCI4078", Latitude=38.23379, Longitude=-75.86963))

XDJ9007_TN_TP_TSS.Complete <- XDJ9007_TN_TP_TSS %>%
  filter(year_month <= as.Date("2013-12-01"))
XDJ9007_TN_TP_TSS.Complete <- XDJ9007_TN_TP_TSS.Complete[order(XDJ9007_TN_TP_TSS.Complete$year_month),]
XDJ9007_TN_TP_TSS.Complete <- XDJ9007_TN_TP_TSS.Complete[!is.na(XDJ9007_TN_TP_TSS.Complete$MonitoringStation),]
```
