``` {r}
#install.packages("wesanderson")
library(wesanderson)
#install.packages("ggsci")
library(ggsci)
#install.packages("viridis")
library(viridis)
#install.packages("RColorBrewer")
library(RColorBrewer)

# Merging Data frames
Plots.Dataframe <- rbind(EE3.0_TN_TP_TSS.Merged,ET6.1_TN_TP_TSS.Merged,ET6.2_TN_TP_TSS.Merged,ET7.1_TN_TP_TSS.Merged,ET8.1_TN_TP_TSS.Merged,ET9.1_TN_TP_TSS.Merged,ET10.1_TN_TP_TSS.Merged)

#Separating year from date column
Plots.Dataframe <- Plots.Dataframe %>% 
  dplyr::mutate(year = lubridate::year(year_month), month= lubridate::month(year_month), day = lubridate::day(year_month))

#Creating yearly average
Yearly.Averages <- Plots.Dataframe %>%
  group_by(MonitoringStation,year) %>%
  summarize(mean_TN = mean(meanTN),
            mean_TP = mean(meanTP),
            mean_TSS = mean(meanTSS))

#Creating dataframes for the averages of all the sites
MeanofYearlyAverages <- Yearly.Averages %>%
  group_by(year) %>%
  summarise_at(vars(mean_TN), list(TNMean= mean))

MeanofYearlyAveragesTP <-Yearly.Averages %>%
  group_by(year) %>%
  summarise_at(vars(mean_TP), list(TPMean= mean))

MeanofYearlyAveragesTSS<- Yearly.Averages %>%
  group_by(year) %>%
  summarise_at(vars(mean_TSS), list(TSSMean= mean))
```

```{r}
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#CC79A7")
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#CC79A7")
grayPallette <-c("#999999", "#999999", "#999999", "#999999", "#999999", "#999999", "#999999", "#FF0000")

#Yearly.TN.Plot <- ggplot() +
  #geom_line(Yearly.Averages, mapping=aes(x=year, y=mean_TN, group=MonitoringStation, color="Monitoringstation")) +
  #geom_line(MeanofYearlyAverages, mapping=aes(x=year, y=TNMean, color="red")) +
  #xlab("Year") +
  #ylab("TN Concentration (mg/L)") + 
  #geom_vline(xintercept = 2010, linetype = "dashed", color = "black", size = 1) +
  #scale_x_continuous(breaks=seq(1985,2025,5)) +
  #scale_color_discrete(name = "Monitoring Stations") + 
  #scale_colour_manual(values = cbbPalette) +
  #scale_colour_manual(values = grayPallette) +
  #geom_smooth(aes(group=1), method= "loess", size =1, se= FALSE, linetype=1, color = "red") 
  #theme_bw() 
Yearly.TN.Plot

Yearly.TN.Plot <- ggplot() +
  geom_line(Yearly.Averages, mapping=aes(x=year, y=mean_TN, group=MonitoringStation), color="gray") +
  geom_line(MeanofYearlyAverages, mapping=aes(x=year, y=TNMean), color="red") +
  xlab("Year") +
  ylab("TN Concentration (mg/L)") + 
  geom_vline(xintercept = 2010, linetype = "dashed", color = "black", size = 1) +
  scale_x_continuous(breaks=seq(1985,2025,5)) +
  theme_bw() 
Yearly.TN.Plot

#Yearly.TP.Plot <- ggplot(Yearly.Averages, aes(x=year, y=mean_TP, group=MonitoringStation, color=MonitoringStation)) +
  #geom_line() +
 # xlab("Year") +
  #ylab("TP Concentration (mg/L)") + 
  #geom_vline(xintercept = 2010, linetype = "dashed", color = "black", size = 1) +
  #scale_x_continuous(breaks=seq(1985,2025,5)) +
  #scale_colour_manual(values = cbbPalette) +
  #theme_bw()
Yearly.TP.Plot

Yearly.TP.Plot <- ggplot() +
  geom_line(Yearly.Averages, mapping=aes(x=year, y=mean_TP, group=MonitoringStation), color="gray") +
  geom_line(MeanofYearlyAveragesTP, mapping=aes(x=year, y=TPMean), color="red") +
  xlab("Year") +
  ylab("TP Concentration (mg/L)") + 
  geom_vline(xintercept = 2010, linetype = "dashed", color = "black", size = 1) +
  scale_x_continuous(breaks=seq(1985,2025,5)) +
  theme_bw() 
Yearly.TP.Plot

#Yearly.TSS.Plot <- ggplot(Yearly.Averages, aes(x=year, y=mean_TSS, group=MonitoringStation, color=MonitoringStation)) +
  #geom_line() +
  #xlab("Year") +
  #ylab("TSS Concentration (mg/L)") + 
  #ggtitle("Concentrations of Total Suspended Solids") +
  #geom_vline(xintercept = 2010, linetype = "dashed", color = "black", size = 1) +
  #scale_x_continuous(breaks=seq(1985,2025,5)) +
  #scale_color_discrete(name = "Monitoring Stations") +
  #theme_bw() +
  #scale_colour_manual(values = cbbPalette)
#Yearly.TSS.Plot

Yearly.TSS.Plot <- ggplot() +
  geom_line(Yearly.Averages, mapping=aes(x=year, y=mean_TSS, group=MonitoringStation), color="gray") +
  geom_line(MeanofYearlyAveragesTSS, mapping=aes(x=year, y=TSSMean), color="red") +
  xlab("Year") +
  ylab("TSS Concentration (mg/L)") + 
  geom_vline(xintercept = 2010, linetype = "dashed", color = "black", size = 1) +
  scale_x_continuous(breaks=seq(1985,2025,5)) +
  theme_bw() 
Yearly.TSS.Plot
```