---
title: "TimeSeries"
author: "Nicole"
date: "2023-11-07"
output: html_document
---
## Objectives
1. Identify nutrient trends over time for each monitoring station
2. Compare to the TSS

## Set up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("tidyverse")
library(tidyverse)
#install.packages("trend")
library(trend)
#install.packages("zoo")
library(zoo)
#install.packages("Kendall")
library(Kendall)
#install.packages("tseries")
library(tseries)
#install.packages("corrplot")
library(corrplot)

#Set Theme
mytheme <- theme_classic(base_size = 14) + theme(axis.text = element_text(color = "black"), legend.position = "top")
theme_set(mytheme)
```

## Import Datasets
```{r}

```

## TN
```{r}
# Create a time series object
BXK0031_TN.ts <- ts(BXK0031_TN_TP_TSS.Complete$meanTN, start = c(2003,3), frequency =12)

#BXK0031_TN.Late.ts <- ts(BXK0031_TN_TP_TSS.Late$TN, start = c(2020,1), end = c(2022, 12), frequency =12)

# Generate the decomposition
BXK0031_TN.Decomposed <- stl(BXK0031_TN.ts, s.window = "periodic")

#BXK0031_TN.Late.Decomposed <- stl(BXK0031_TN.Late.ts, s.window = "periodic")

#Visualize the decomposed series
plot(BXK0031_TN.Decomposed)

#plot(BXK0031_TN.Late.Decomposed)

#Running Mann-Kendall Test
BXK0031.MK.TN <- MannKendall(BXK0031_TN.ts)
BXK0031.MK.TN
summary(BXK0031.MK.TN)

#Visualize Trend ## what does this mean??
plot(BXK0031_TN.ts)
lines(lowess(time(BXK0031_TN.ts), BXK0031_TN.ts), col= 'blue')

## Visualize with ggplot
BXK0031_TN_plot <- ggplot(BXK0031_TN_TP_TSS.Complete, aes(x=year_month, y=meanTN)) +
  geom_line() +
  geom_smooth(method="loess", se=F) +
  xlab("Year") +
  ylab("Total Nitrogen (mg)")
BXK0031_TN_plot

#Running Seasonal MK
# BXK0031.Early.SMK <- SeasonalMannKendall(BXK0031_TN.Early.ts)
# summary(BXK0031.Early.SMK)
```

#TP
```{r}
# Create a time series object
BXK0031_TP.ts <- ts(BXK0031_TN_TP_TSS.Complete$meanTP, start = c(2003,3), frequency =12)

# Generate the decomposition
BXK0031_TP.Decomposed <- stl(BXK0031_TP.ts, s.window = "periodic")

#Visualize the decomposed series
plot(BXK0031_TP.Decomposed)

#Running Mann-Kendall Test
BXK0031.MK.TP <- MannKendall(BXK0031_TP.ts)
BXK0031.MK.TP
summary(BXK0031.MK.TP)

##Visualize with ggplot
BXK0031_TP_plot <- ggplot(BXK0031_TN_TP_TSS.Complete, aes(x=year_month, y=meanTP)) +
  geom_line() +
  geom_smooth(method="loess", se=F) +
  xlab("Year") +
  ylab("Total Phosphorus (mg)")
BXK0031_TP_plot
```

#TSS
```{r}
# Create a time series object
BXK0031_TSS.ts <- ts(BXK0031_TN_TP_TSS.Complete$meanTSS, start = c(2003,3), frequency =12)

# Generate the decomposition
BXK0031_TSS.Decomposed <- stl(BXK0031_TSS.ts, s.window = "periodic")

# Visualize the decomposed series
plot(BXK0031_TSS.Decomposed)

#Running Mann-Kendall Test
BXK0031.MK.TSS <- MannKendall(BXK0031_TSS.ts)
BXK0031.MK.TSS
summary(BXK0031.MK.TSS)

##Visualize with ggplot
BXK0031_TSS_plot <- ggplot(BXK0031_TN_TP_TSS.Complete, aes(x=year_month, y=meanTSS)) +
  geom_line() +
  geom_smooth(method="loess", se=F) +
  xlab("Year") +
  ylab("Total Suspended Solids (mg)")
BXK0031_TSS_plot
```

```{r}
#Correlation Plots
BXK0031_CorrPrep <- BXK0031_TN_TP_TSS.Complete[,c(5:7)]
testRes = cor.mtest(BXK0031_CorrPrep, conf.level = 0.95)
BXK0031.Corr <- cor(BXK0031_CorrPrep) 
corrplot(BXK0031.Corr, p.mat = testRes$p, method = "circle", insig = 'blank', addCoef.col ='white',number.cex = 0.8, order = 'AOE', diag=TRUE)
```