---
title: "TimeSeries"
author: "Nicole"
date: "2023-11-07"
output: html_document
---
## Objectives
1. Identify nutrient trends over time for each monitoring station
2. Compare to the TSS

## Set up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("tidyverse")
library(tidyverse)
#install.packages("trend")
library(trend)
#install.packages("zoo")
library(zoo)
#install.packages("Kendall")
library(Kendall)
#install.packages("tseries")
library(tseries)


#Set Theme
mytheme <- theme_classic(base_size = 14) + theme(axis.text = element_text(color = "black"), legend.position = "top")
theme_set(mytheme)
```

## Import Datasets
```{r}

```

## Decomposing datasets for time series
```{r}
# Create a time series object
BXK0031_TN.Early.ts <- ts(BXK0031_TN_TP_TSS.Early$TN, start = c(2003,3), end = c(2013, 12), frequency =12)

BXK0031_TN.Late.ts <- ts(BXK0031_TN_TP_TSS.Late$TN, start = c(2020,1), end = c(2022, 12), frequency =12)

# Generate the decomposition
BXK0031_TN.Early.Decomposed <- stl(BXK0031_TN.Early.ts, s.window = "periodic")

BXK0031_TN.Late.Decomposed <- stl(BXK0031_TN.Late.ts, s.window = "periodic")

#Visualize the decomposed series
plot(BXK0031_TN.Early.Decomposed)

plot(BXK0031_TN.Late.Decomposed)

#Running Mann-Kendall Test
BXK0031.Early.MK <- MannKendall(BXK0031_TN.Early.ts)
BXK0031.Early.MK
summary(BXK0031.Early.MK)

#Visualize Trend ## what does this mean??
plot(BXK0031_TN.Early.ts)
lines(lowess(time(BXK0031_TN.Early.ts), BXK0031_TN.Early.ts), col= 'blue')

#Running Seasonal MK
BXK0031.Early.SMK <- SeasonalMannKendall(BXK0031_TN.Early.ts)
summary(BXK0031.Early.SMK)

```